//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.0.
// 
#pragma warning disable 1591

namespace WcfConnectPaysbuy.get_ws_dtacReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="get_ws_dtacSoap", Namespace="http://tempuri.org/")]
    public partial class get_ws_dtac : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback api_paynow_happy_refillOperationCompleted;
        
        private System.Threading.SendOrPostCallback api_happy_verifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback api_happy_confirmOperationCompleted;
        
        private System.Threading.SendOrPostCallback postpaid_request_queryOperationCompleted;
        
        private System.Threading.SendOrPostCallback postpaid_request_confirmOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public get_ws_dtac() {
            this.Url = global::WcfConnectPaysbuy.Properties.Settings.Default.WcfConnectPaysbuy_get_ws_dtacReference_get_ws_dtac;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event api_paynow_happy_refillCompletedEventHandler api_paynow_happy_refillCompleted;
        
        /// <remarks/>
        public event api_happy_verifyCompletedEventHandler api_happy_verifyCompleted;
        
        /// <remarks/>
        public event api_happy_confirmCompletedEventHandler api_happy_confirmCompleted;
        
        /// <remarks/>
        public event postpaid_request_queryCompletedEventHandler postpaid_request_queryCompleted;
        
        /// <remarks/>
        public event postpaid_request_confirmCompletedEventHandler postpaid_request_confirmCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/api_paynow_happy_refill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string api_paynow_happy_refill(string psbID, string username, string secureCode, double amt, string ref1, string inv, string method, string language, string opt_fix_method, string resp_front_url, string opt_name, string opt_email) {
            object[] results = this.Invoke("api_paynow_happy_refill", new object[] {
                        psbID,
                        username,
                        secureCode,
                        amt,
                        ref1,
                        inv,
                        method,
                        language,
                        opt_fix_method,
                        resp_front_url,
                        opt_name,
                        opt_email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void api_paynow_happy_refillAsync(string psbID, string username, string secureCode, double amt, string ref1, string inv, string method, string language, string opt_fix_method, string resp_front_url, string opt_name, string opt_email) {
            this.api_paynow_happy_refillAsync(psbID, username, secureCode, amt, ref1, inv, method, language, opt_fix_method, resp_front_url, opt_name, opt_email, null);
        }
        
        /// <remarks/>
        public void api_paynow_happy_refillAsync(string psbID, string username, string secureCode, double amt, string ref1, string inv, string method, string language, string opt_fix_method, string resp_front_url, string opt_name, string opt_email, object userState) {
            if ((this.api_paynow_happy_refillOperationCompleted == null)) {
                this.api_paynow_happy_refillOperationCompleted = new System.Threading.SendOrPostCallback(this.Onapi_paynow_happy_refillOperationCompleted);
            }
            this.InvokeAsync("api_paynow_happy_refill", new object[] {
                        psbID,
                        username,
                        secureCode,
                        amt,
                        ref1,
                        inv,
                        method,
                        language,
                        opt_fix_method,
                        resp_front_url,
                        opt_name,
                        opt_email}, this.api_paynow_happy_refillOperationCompleted, userState);
        }
        
        private void Onapi_paynow_happy_refillOperationCompleted(object arg) {
            if ((this.api_paynow_happy_refillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.api_paynow_happy_refillCompleted(this, new api_paynow_happy_refillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/api_happy_verify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string api_happy_verify(string psbID, string inv, string Channel, string ref1, decimal amt) {
            object[] results = this.Invoke("api_happy_verify", new object[] {
                        psbID,
                        inv,
                        Channel,
                        ref1,
                        amt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void api_happy_verifyAsync(string psbID, string inv, string Channel, string ref1, decimal amt) {
            this.api_happy_verifyAsync(psbID, inv, Channel, ref1, amt, null);
        }
        
        /// <remarks/>
        public void api_happy_verifyAsync(string psbID, string inv, string Channel, string ref1, decimal amt, object userState) {
            if ((this.api_happy_verifyOperationCompleted == null)) {
                this.api_happy_verifyOperationCompleted = new System.Threading.SendOrPostCallback(this.Onapi_happy_verifyOperationCompleted);
            }
            this.InvokeAsync("api_happy_verify", new object[] {
                        psbID,
                        inv,
                        Channel,
                        ref1,
                        amt}, this.api_happy_verifyOperationCompleted, userState);
        }
        
        private void Onapi_happy_verifyOperationCompleted(object arg) {
            if ((this.api_happy_verifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.api_happy_verifyCompleted(this, new api_happy_verifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/api_happy_confirm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string api_happy_confirm(string inv, string tranlog_id) {
            object[] results = this.Invoke("api_happy_confirm", new object[] {
                        inv,
                        tranlog_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void api_happy_confirmAsync(string inv, string tranlog_id) {
            this.api_happy_confirmAsync(inv, tranlog_id, null);
        }
        
        /// <remarks/>
        public void api_happy_confirmAsync(string inv, string tranlog_id, object userState) {
            if ((this.api_happy_confirmOperationCompleted == null)) {
                this.api_happy_confirmOperationCompleted = new System.Threading.SendOrPostCallback(this.Onapi_happy_confirmOperationCompleted);
            }
            this.InvokeAsync("api_happy_confirm", new object[] {
                        inv,
                        tranlog_id}, this.api_happy_confirmOperationCompleted, userState);
        }
        
        private void Onapi_happy_confirmOperationCompleted(object arg) {
            if ((this.api_happy_confirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.api_happy_confirmCompleted(this, new api_happy_confirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/postpaid_request_query", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public returnPostpaidRequest[] postpaid_request_query(string secureCode, string paymentChannel, string paymentType, string tid, decimal amt, string mobileNo, string email) {
            object[] results = this.Invoke("postpaid_request_query", new object[] {
                        secureCode,
                        paymentChannel,
                        paymentType,
                        tid,
                        amt,
                        mobileNo,
                        email});
            return ((returnPostpaidRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void postpaid_request_queryAsync(string secureCode, string paymentChannel, string paymentType, string tid, decimal amt, string mobileNo, string email) {
            this.postpaid_request_queryAsync(secureCode, paymentChannel, paymentType, tid, amt, mobileNo, email, null);
        }
        
        /// <remarks/>
        public void postpaid_request_queryAsync(string secureCode, string paymentChannel, string paymentType, string tid, decimal amt, string mobileNo, string email, object userState) {
            if ((this.postpaid_request_queryOperationCompleted == null)) {
                this.postpaid_request_queryOperationCompleted = new System.Threading.SendOrPostCallback(this.Onpostpaid_request_queryOperationCompleted);
            }
            this.InvokeAsync("postpaid_request_query", new object[] {
                        secureCode,
                        paymentChannel,
                        paymentType,
                        tid,
                        amt,
                        mobileNo,
                        email}, this.postpaid_request_queryOperationCompleted, userState);
        }
        
        private void Onpostpaid_request_queryOperationCompleted(object arg) {
            if ((this.postpaid_request_queryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postpaid_request_queryCompleted(this, new postpaid_request_queryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/postpaid_request_confirm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public returnPostpaidConfirm[] postpaid_request_confirm(string secureCode, string tid, string refID, decimal amt, string confirmStatus, string bankTrxId) {
            object[] results = this.Invoke("postpaid_request_confirm", new object[] {
                        secureCode,
                        tid,
                        refID,
                        amt,
                        confirmStatus,
                        bankTrxId});
            return ((returnPostpaidConfirm[])(results[0]));
        }
        
        /// <remarks/>
        public void postpaid_request_confirmAsync(string secureCode, string tid, string refID, decimal amt, string confirmStatus, string bankTrxId) {
            this.postpaid_request_confirmAsync(secureCode, tid, refID, amt, confirmStatus, bankTrxId, null);
        }
        
        /// <remarks/>
        public void postpaid_request_confirmAsync(string secureCode, string tid, string refID, decimal amt, string confirmStatus, string bankTrxId, object userState) {
            if ((this.postpaid_request_confirmOperationCompleted == null)) {
                this.postpaid_request_confirmOperationCompleted = new System.Threading.SendOrPostCallback(this.Onpostpaid_request_confirmOperationCompleted);
            }
            this.InvokeAsync("postpaid_request_confirm", new object[] {
                        secureCode,
                        tid,
                        refID,
                        amt,
                        confirmStatus,
                        bankTrxId}, this.postpaid_request_confirmOperationCompleted, userState);
        }
        
        private void Onpostpaid_request_confirmOperationCompleted(object arg) {
            if ((this.postpaid_request_confirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postpaid_request_confirmCompleted(this, new postpaid_request_confirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class returnPostpaidRequest {
        
        private string tidField;
        
        private string respCodeField;
        
        private string respMessageField;
        
        private string minField;
        
        private string maxField;
        
        private string totalField;
        
        private string balanceField;
        
        private string reconnectField;
        
        private string refIdField;
        
        /// <remarks/>
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respMessage {
            get {
                return this.respMessageField;
            }
            set {
                this.respMessageField = value;
            }
        }
        
        /// <remarks/>
        public string min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
        
        /// <remarks/>
        public string max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string reconnect {
            get {
                return this.reconnectField;
            }
            set {
                this.reconnectField = value;
            }
        }
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class returnPostpaidConfirm {
        
        private string tidField;
        
        private string respCodeField;
        
        private string respMessageField;
        
        private string refIdField;
        
        /// <remarks/>
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respMessage {
            get {
                return this.respMessageField;
            }
            set {
                this.respMessageField = value;
            }
        }
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    public delegate void api_paynow_happy_refillCompletedEventHandler(object sender, api_paynow_happy_refillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class api_paynow_happy_refillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal api_paynow_happy_refillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    public delegate void api_happy_verifyCompletedEventHandler(object sender, api_happy_verifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class api_happy_verifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal api_happy_verifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    public delegate void api_happy_confirmCompletedEventHandler(object sender, api_happy_confirmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class api_happy_confirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal api_happy_confirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    public delegate void postpaid_request_queryCompletedEventHandler(object sender, postpaid_request_queryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postpaid_request_queryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postpaid_request_queryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnPostpaidRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnPostpaidRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    public delegate void postpaid_request_confirmCompletedEventHandler(object sender, postpaid_request_confirmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postpaid_request_confirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postpaid_request_confirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnPostpaidConfirm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnPostpaidConfirm[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591