//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.0.
// 
#pragma warning disable 1591

namespace WcfConnectPaysbuy.MBAReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="getToppingSoap", Namespace="http://tempuri.org/")]
    public partial class getTopping : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback mea_request_queryOperationCompleted;
        
        private System.Threading.SendOrPostCallback mea_request_confirmOperationCompleted;
        
        private System.Threading.SendOrPostCallback mwa_request_queryOperationCompleted;
        
        private System.Threading.SendOrPostCallback mwa_request_confirmOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public getTopping() {
            this.Url = global::WcfConnectPaysbuy.Properties.Settings.Default.WcfConnectPaysbuy_MBAReference_getTopping;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event mea_request_queryCompletedEventHandler mea_request_queryCompleted;
        
        /// <remarks/>
        public event mea_request_confirmCompletedEventHandler mea_request_confirmCompleted;
        
        /// <remarks/>
        public event mwa_request_queryCompletedEventHandler mwa_request_queryCompleted;
        
        /// <remarks/>
        public event mwa_request_confirmCompletedEventHandler mwa_request_confirmCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mea_request_query", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public returnMeaRequest[] mea_request_query(string secureCode, string tid, string contractAC, string email, string mobileNo) {
            object[] results = this.Invoke("mea_request_query", new object[] {
                        secureCode,
                        tid,
                        contractAC,
                        email,
                        mobileNo});
            return ((returnMeaRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void mea_request_queryAsync(string secureCode, string tid, string contractAC, string email, string mobileNo) {
            this.mea_request_queryAsync(secureCode, tid, contractAC, email, mobileNo, null);
        }
        
        /// <remarks/>
        public void mea_request_queryAsync(string secureCode, string tid, string contractAC, string email, string mobileNo, object userState) {
            if ((this.mea_request_queryOperationCompleted == null)) {
                this.mea_request_queryOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmea_request_queryOperationCompleted);
            }
            this.InvokeAsync("mea_request_query", new object[] {
                        secureCode,
                        tid,
                        contractAC,
                        email,
                        mobileNo}, this.mea_request_queryOperationCompleted, userState);
        }
        
        private void Onmea_request_queryOperationCompleted(object arg) {
            if ((this.mea_request_queryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mea_request_queryCompleted(this, new mea_request_queryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mea_request_confirm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public returnMeaConfirm[] mea_request_confirm(string secureCode, string tid, string refID, decimal amt, decimal fee, string confirmStatus, string cardsNo, string bankTrxId) {
            object[] results = this.Invoke("mea_request_confirm", new object[] {
                        secureCode,
                        tid,
                        refID,
                        amt,
                        fee,
                        confirmStatus,
                        cardsNo,
                        bankTrxId});
            return ((returnMeaConfirm[])(results[0]));
        }
        
        /// <remarks/>
        public void mea_request_confirmAsync(string secureCode, string tid, string refID, decimal amt, decimal fee, string confirmStatus, string cardsNo, string bankTrxId) {
            this.mea_request_confirmAsync(secureCode, tid, refID, amt, fee, confirmStatus, cardsNo, bankTrxId, null);
        }
        
        /// <remarks/>
        public void mea_request_confirmAsync(string secureCode, string tid, string refID, decimal amt, decimal fee, string confirmStatus, string cardsNo, string bankTrxId, object userState) {
            if ((this.mea_request_confirmOperationCompleted == null)) {
                this.mea_request_confirmOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmea_request_confirmOperationCompleted);
            }
            this.InvokeAsync("mea_request_confirm", new object[] {
                        secureCode,
                        tid,
                        refID,
                        amt,
                        fee,
                        confirmStatus,
                        cardsNo,
                        bankTrxId}, this.mea_request_confirmOperationCompleted, userState);
        }
        
        private void Onmea_request_confirmOperationCompleted(object arg) {
            if ((this.mea_request_confirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mea_request_confirmCompleted(this, new mea_request_confirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mwa_request_query", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public returnMwaRequest[] mwa_request_query(string secureCode, string tid, string taxID, string suffix, string ref1, string ref2, decimal amount, string name, string address, string email, string mobileNo) {
            object[] results = this.Invoke("mwa_request_query", new object[] {
                        secureCode,
                        tid,
                        taxID,
                        suffix,
                        ref1,
                        ref2,
                        amount,
                        name,
                        address,
                        email,
                        mobileNo});
            return ((returnMwaRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void mwa_request_queryAsync(string secureCode, string tid, string taxID, string suffix, string ref1, string ref2, decimal amount, string name, string address, string email, string mobileNo) {
            this.mwa_request_queryAsync(secureCode, tid, taxID, suffix, ref1, ref2, amount, name, address, email, mobileNo, null);
        }
        
        /// <remarks/>
        public void mwa_request_queryAsync(string secureCode, string tid, string taxID, string suffix, string ref1, string ref2, decimal amount, string name, string address, string email, string mobileNo, object userState) {
            if ((this.mwa_request_queryOperationCompleted == null)) {
                this.mwa_request_queryOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmwa_request_queryOperationCompleted);
            }
            this.InvokeAsync("mwa_request_query", new object[] {
                        secureCode,
                        tid,
                        taxID,
                        suffix,
                        ref1,
                        ref2,
                        amount,
                        name,
                        address,
                        email,
                        mobileNo}, this.mwa_request_queryOperationCompleted, userState);
        }
        
        private void Onmwa_request_queryOperationCompleted(object arg) {
            if ((this.mwa_request_queryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mwa_request_queryCompleted(this, new mwa_request_queryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mwa_request_confirm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public returnMwaConfirm[] mwa_request_confirm(string secureCode, string tid, string refID, decimal amount, decimal fee, string confirmStatus, string cardsNo, string bankTrxId) {
            object[] results = this.Invoke("mwa_request_confirm", new object[] {
                        secureCode,
                        tid,
                        refID,
                        amount,
                        fee,
                        confirmStatus,
                        cardsNo,
                        bankTrxId});
            return ((returnMwaConfirm[])(results[0]));
        }
        
        /// <remarks/>
        public void mwa_request_confirmAsync(string secureCode, string tid, string refID, decimal amount, decimal fee, string confirmStatus, string cardsNo, string bankTrxId) {
            this.mwa_request_confirmAsync(secureCode, tid, refID, amount, fee, confirmStatus, cardsNo, bankTrxId, null);
        }
        
        /// <remarks/>
        public void mwa_request_confirmAsync(string secureCode, string tid, string refID, decimal amount, decimal fee, string confirmStatus, string cardsNo, string bankTrxId, object userState) {
            if ((this.mwa_request_confirmOperationCompleted == null)) {
                this.mwa_request_confirmOperationCompleted = new System.Threading.SendOrPostCallback(this.Onmwa_request_confirmOperationCompleted);
            }
            this.InvokeAsync("mwa_request_confirm", new object[] {
                        secureCode,
                        tid,
                        refID,
                        amount,
                        fee,
                        confirmStatus,
                        cardsNo,
                        bankTrxId}, this.mwa_request_confirmOperationCompleted, userState);
        }
        
        private void Onmwa_request_confirmOperationCompleted(object arg) {
            if ((this.mwa_request_confirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mwa_request_confirmCompleted(this, new mwa_request_confirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class returnMeaRequest {
        
        private string tidField;
        
        private string respCodeField;
        
        private string respMessageField;
        
        private string nameField;
        
        private string addressField;
        
        private string ref1Field;
        
        private string dueDateField;
        
        private string amountField;
        
        private string invoiceDateField;
        
        private string discountAmountField;
        
        private string refIdField;
        
        /// <remarks/>
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respMessage {
            get {
                return this.respMessageField;
            }
            set {
                this.respMessageField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string ref1 {
            get {
                return this.ref1Field;
            }
            set {
                this.ref1Field = value;
            }
        }
        
        /// <remarks/>
        public string dueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
            }
        }
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string invoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        public string discountAmount {
            get {
                return this.discountAmountField;
            }
            set {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class returnMwaConfirm {
        
        private string tidField;
        
        private string respCodeField;
        
        private string respMessageField;
        
        private string refIdField;
        
        /// <remarks/>
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respMessage {
            get {
                return this.respMessageField;
            }
            set {
                this.respMessageField = value;
            }
        }
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class returnMwaRequest {
        
        private string tidField;
        
        private string respCodeField;
        
        private string respMessageField;
        
        private string refIdField;
        
        /// <remarks/>
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respMessage {
            get {
                return this.respMessageField;
            }
            set {
                this.respMessageField = value;
            }
        }
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class returnMeaConfirm {
        
        private string tidField;
        
        private string respCodeField;
        
        private string respMessageField;
        
        private string refIdField;
        
        /// <remarks/>
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respMessage {
            get {
                return this.respMessageField;
            }
            set {
                this.respMessageField = value;
            }
        }
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    public delegate void mea_request_queryCompletedEventHandler(object sender, mea_request_queryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mea_request_queryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mea_request_queryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnMeaRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnMeaRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    public delegate void mea_request_confirmCompletedEventHandler(object sender, mea_request_confirmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mea_request_confirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mea_request_confirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnMeaConfirm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnMeaConfirm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    public delegate void mwa_request_queryCompletedEventHandler(object sender, mwa_request_queryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mwa_request_queryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mwa_request_queryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnMwaRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnMwaRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    public delegate void mwa_request_confirmCompletedEventHandler(object sender, mwa_request_confirmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mwa_request_confirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mwa_request_confirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnMwaConfirm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnMwaConfirm[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591